//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobility_Android.Activities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceFR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceFR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mobility_Android.Activities.ResourceFR", typeof(ResourceFR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 - Creation de palette.
        /// </summary>
        internal static string btnAddPalette {
            get {
                return ResourceManager.GetString("btnAddPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer.
        /// </summary>
        internal static string btnConfirm {
            get {
                return ResourceManager.GetString("btnConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion.
        /// </summary>
        internal static string btnConnect {
            get {
                return ResourceManager.GetString("btnConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consolidation.
        /// </summary>
        internal static string btnConsolidate {
            get {
                return ResourceManager.GetString("btnConsolidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminer.
        /// </summary>
        internal static string btnEnd {
            get {
                return ResourceManager.GetString("btnEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commande terminée.
        /// </summary>
        internal static string btnEndPicking {
            get {
                return ResourceManager.GetString("btnEndPicking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palette terminée.
        /// </summary>
        internal static string btnEndPickingPalette {
            get {
                return ResourceManager.GetString("btnEndPickingPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réception terminée.
        /// </summary>
        internal static string btnEndReceiving {
            get {
                return ResourceManager.GetString("btnEndReceiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déconnexion.
        /// </summary>
        internal static string btnExit {
            get {
                return ResourceManager.GetString("btnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations.
        /// </summary>
        internal static string btnInfo {
            get {
                return ResourceManager.GetString("btnInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déconnexion.
        /// </summary>
        internal static string btnLogout {
            get {
                return ResourceManager.GetString("btnLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - Déplacement.
        /// </summary>
        internal static string btnMove {
            get {
                return ResourceManager.GetString("btnMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string btnNewINterWarehouse {
            get {
                return ResourceManager.GetString("btnNewINterWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commande.
        /// </summary>
        internal static string btnPicking {
            get {
                return ResourceManager.GetString("btnPicking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 - Production.
        /// </summary>
        internal static string btnProduction {
            get {
                return ResourceManager.GetString("btnProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - Mise en production.
        /// </summary>
        internal static string btnPutProduction {
            get {
                return ResourceManager.GetString("btnPutProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réception .
        /// </summary>
        internal static string btnRecieve {
            get {
                return ResourceManager.GetString("btnRecieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relocalisation.
        /// </summary>
        internal static string btnRelocation {
            get {
                return ResourceManager.GetString("btnRelocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder.
        /// </summary>
        internal static string btnSaveConfig {
            get {
                return ResourceManager.GetString("btnSaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de joindre le webservice.
        /// </summary>
        internal static string errCannotReachWebservice {
            get {
                return ResourceManager.GetString("errCannotReachWebservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreure est survenue lors de la création de la palette.
        /// </summary>
        internal static string errConfirmingPallet {
            get {
                return ResourceManager.GetString("errConfirmingPallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez rentrer un code pour la licence.
        /// </summary>
        internal static string errEmptyFieldLicense {
            get {
                return ResourceManager.GetString("errEmptyFieldLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le code barre n&apos;est pas valide. Tag non reconnu .
        /// </summary>
        internal static string errInvalidStringFormat {
            get {
                return ResourceManager.GetString("errInvalidStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La licence à déja été cueillie.
        /// </summary>
        internal static string errLicAlreadyPicked {
            get {
                return ResourceManager.GetString("errLicAlreadyPicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un item doit être sélectionné.
        /// </summary>
        internal static string errNoItemSelected {
            get {
                return ResourceManager.GetString("errNoItemSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La palette doit être confirmée avant de cueillir un autre produit.
        /// </summary>
        internal static string errNotCurrentProduct {
            get {
                return ResourceManager.GetString("errNotCurrentProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cueillette complétée.
        /// </summary>
        internal static string errPickingCompleted {
            get {
                return ResourceManager.GetString("errPickingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cueillette non complétée.
        /// </summary>
        internal static string errPickingNonCompleted {
            get {
                return ResourceManager.GetString("errPickingNonCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La licence n&apos;a pas de poids.
        /// </summary>
        internal static string errProductHasNoWeight {
            get {
                return ResourceManager.GetString("errProductHasNoWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le produit ne fait pas parti due l&apos;item courant.
        /// </summary>
        internal static string errProductNotPresent {
            get {
                return ResourceManager.GetString("errProductNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réception complétée.
        /// </summary>
        internal static string errReceptionCompleted {
            get {
                return ResourceManager.GetString("errReceptionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réception non complétée.
        /// </summary>
        internal static string errReceptionNonCompleted {
            get {
                return ResourceManager.GetString("errReceptionNonCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relocation complétée.
        /// </summary>
        internal static string errRelocCompleted {
            get {
                return ResourceManager.GetString("errRelocCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relocation non complétée.
        /// </summary>
        internal static string errRelocNonCompleted {
            get {
                return ResourceManager.GetString("errRelocNonCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le termicon a été notifié pour l&apos;impression.
        /// </summary>
        internal static string errTermiconNotified {
            get {
                return ResourceManager.GetString("errTermiconNotified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de notifier le termicon pour l&apos;impression.
        /// </summary>
        internal static string errTermiconNotNotified {
            get {
                return ResourceManager.GetString("errTermiconNotNotified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changement d&apos;entrepot réussi.
        /// </summary>
        internal static string errWarehouseChanged {
            get {
                return ResourceManager.GetString("errWarehouseChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de changer d&apos;entrepot.
        /// </summary>
        internal static string errWarehouseNotChanged {
            get {
                return ResourceManager.GetString("errWarehouseNotChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur s&apos;est produite lors de l&apos;acces au service Web.
        /// </summary>
        internal static string errWebserviceGeneric {
            get {
                return ResourceManager.GetString("errWebserviceGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;URL du service web est incorrect.
        /// </summary>
        internal static string errWebServiceUrlIncorrect {
            get {
                return ResourceManager.GetString("errWebServiceUrlIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client :.
        /// </summary>
        internal static string lblClient {
            get {
                return ResourceManager.GetString("lblClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date :.
        /// </summary>
        internal static string lblDate {
            get {
                return ResourceManager.GetString("lblDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date d&apos;expédition prévue:.
        /// </summary>
        internal static string lblDateSale {
            get {
                return ResourceManager.GetString("lblDateSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propriétaire :.
        /// </summary>
        internal static string lblOwner {
            get {
                return ResourceManager.GetString("lblOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO :.
        /// </summary>
        internal static string lblPO {
            get {
                return ResourceManager.GetString("lblPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produit :.
        /// </summary>
        internal static string lblProduct {
            get {
                return ResourceManager.GetString("lblProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qté / udm :.
        /// </summary>
        internal static string lblQty {
            get {
                return ResourceManager.GetString("lblQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination :.
        /// </summary>
        internal static string lblRecipient {
            get {
                return ResourceManager.GetString("lblRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information de licence.
        /// </summary>
        internal static string lblTitleLicenseInfo {
            get {
                return ResourceManager.GetString("lblTitleLicenseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Création de commande.
        /// </summary>
        internal static string lblTitleSaleInfo {
            get {
                return ResourceManager.GetString("lblTitleSaleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poids :.
        /// </summary>
        internal static string lblWeight {
            get {
                return ResourceManager.GetString("lblWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accueil.
        /// </summary>
        internal static string menuHome {
            get {
                return ResourceManager.GetString("menuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déplacement.
        /// </summary>
        internal static string menuMove {
            get {
                return ResourceManager.GetString("menuMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commande.
        /// </summary>
        internal static string menuPicking {
            get {
                return ResourceManager.GetString("menuPicking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réception.
        /// </summary>
        internal static string menuRecieving {
            get {
                return ResourceManager.GetString("menuRecieving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anglais.
        /// </summary>
        internal static string rbEnglish {
            get {
                return ResourceManager.GetString("rbEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        internal static string rbFrench {
            get {
                return ResourceManager.GetString("rbFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2255 Boulevard Fernand-Lafontaine, #300.
        /// </summary>
        internal static string tvAddress1 {
            get {
                return ResourceManager.GetString("tvAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longueuil, QC, J4G 2R8.
        /// </summary>
        internal static string tvAddress2 {
            get {
                return ResourceManager.GetString("tvAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client :.
        /// </summary>
        internal static string tvClient {
            get {
                return ResourceManager.GetString("tvClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurations.
        /// </summary>
        internal static string tvConfig {
            get {
                return ResourceManager.GetString("tvConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consolidation.
        /// </summary>
        internal static string tvConsolidation {
            get {
                return ResourceManager.GetString("tvConsolidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productions.
        /// </summary>
        internal static string tvCreation {
            get {
                return ResourceManager.GetString("tvCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CS.
        /// </summary>
        internal static string tvCS {
            get {
                return ResourceManager.GetString("tvCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        internal static string tvCustomer {
            get {
                return ResourceManager.GetString("tvCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déplacement.
        /// </summary>
        internal static string tvDeplacement {
            get {
                return ResourceManager.GetString("tvDeplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination :.
        /// </summary>
        internal static string tvDestination {
            get {
                return ResourceManager.GetString("tvDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support@ceritar.com.
        /// </summary>
        internal static string tvEmail {
            get {
                return ResourceManager.GetString("tvEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fournisseur.
        /// </summary>
        internal static string tvFournisseur {
            get {
                return ResourceManager.GetString("tvFournisseur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gabarit.
        /// </summary>
        internal static string tvGabarit {
            get {
                return ResourceManager.GetString("tvGabarit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations.
        /// </summary>
        internal static string tvInfo {
            get {
                return ResourceManager.GetString("tvInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # :.
        /// </summary>
        internal static string tvInterWarehouse {
            get {
                return ResourceManager.GetString("tvInterWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ip :.
        /// </summary>
        internal static string tvIp {
            get {
                return ResourceManager.GetString("tvIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence :.
        /// </summary>
        internal static string tvLicence {
            get {
                return ResourceManager.GetString("tvLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence :.
        /// </summary>
        internal static string tvLicense {
            get {
                return ResourceManager.GetString("tvLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ligne.
        /// </summary>
        internal static string tvLigne {
            get {
                return ResourceManager.GetString("tvLigne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ligne.
        /// </summary>
        internal static string tvLine {
            get {
                return ResourceManager.GetString("tvLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déconnexion.
        /// </summary>
        internal static string tvLogout {
            get {
                return ResourceManager.GetString("tvLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;utilisateur :.
        /// </summary>
        internal static string tvName {
            get {
                return ResourceManager.GetString("tvName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NRI.
        /// </summary>
        internal static string tvNRI {
            get {
                return ResourceManager.GetString("tvNRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL du serveur :.
        /// </summary>
        internal static string tvOrder {
            get {
                return ResourceManager.GetString("tvOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palette :.
        /// </summary>
        internal static string tvPalette {
            get {
                return ResourceManager.GetString("tvPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe :.
        /// </summary>
        internal static string tvPass {
            get {
                return ResourceManager.GetString("tvPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez entrer le mot de passe :.
        /// </summary>
        internal static string tvPassPrompt {
            get {
                return ResourceManager.GetString("tvPassPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (450) 651-9988.
        /// </summary>
        internal static string tvPhoneNumber {
            get {
                return ResourceManager.GetString("tvPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Commande :.
        /// </summary>
        internal static string tvPicking {
            get {
                return ResourceManager.GetString("tvPicking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poids :.
        /// </summary>
        internal static string tvPoids {
            get {
                return ResourceManager.GetString("tvPoids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port :.
        /// </summary>
        internal static string tvPort {
            get {
                return ResourceManager.GetString("tvPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Bon de travail.
        /// </summary>
        internal static string tvProdOrder {
            get {
                return ResourceManager.GetString("tvProdOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produit :.
        /// </summary>
        internal static string tvProduct {
            get {
                return ResourceManager.GetString("tvProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails du produit.
        /// </summary>
        internal static string tvProductDetails {
            get {
                return ResourceManager.GetString("tvProductDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produit.
        /// </summary>
        internal static string tvProductEntete {
            get {
                return ResourceManager.GetString("tvProductEntete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produit.
        /// </summary>
        internal static string tvProductName {
            get {
                return ResourceManager.GetString("tvProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fournisseur :.
        /// </summary>
        internal static string tvProvider {
            get {
                return ResourceManager.GetString("tvProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mise en production.
        /// </summary>
        internal static string tvPutProduction {
            get {
                return ResourceManager.GetString("tvPutProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qté :.
        /// </summary>
        internal static string tvQte {
            get {
                return ResourceManager.GetString("tvQte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantité.
        /// </summary>
        internal static string tvQtyEntete {
            get {
                return ResourceManager.GetString("tvQtyEntete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantité.
        /// </summary>
        internal static string tvQuantity {
            get {
                return ResourceManager.GetString("tvQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Rec..
        /// </summary>
        internal static string tvRec {
            get {
                return ResourceManager.GetString("tvRec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réceptions.
        /// </summary>
        internal static string tvReceiving {
            get {
                return ResourceManager.GetString("tvReceiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Réception :.
        /// </summary>
        internal static string tvRecieving {
            get {
                return ResourceManager.GetString("tvRecieving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Commande.
        /// </summary>
        internal static string tvSale {
            get {
                return ResourceManager.GetString("tvSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select..
        /// </summary>
        internal static string tvSelect {
            get {
                return ResourceManager.GetString("tvSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station :.
        /// </summary>
        internal static string tvStation {
            get {
                return ResourceManager.GetString("tvStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template :.
        /// </summary>
        internal static string tvTemplate {
            get {
                return ResourceManager.GetString("tvTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serveur d&apos;impression :.
        /// </summary>
        internal static string tvTermicon {
            get {
                return ResourceManager.GetString("tvTermicon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inter entrepôt.
        /// </summary>
        internal static string tvTitleInterWarehouse {
            get {
                return ResourceManager.GetString("tvTitleInterWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commande.
        /// </summary>
        internal static string tvTitlePicking {
            get {
                return ResourceManager.GetString("tvTitlePicking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bon de production.
        /// </summary>
        internal static string tvTitleProdOrder {
            get {
                return ResourceManager.GetString("tvTitleProdOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réception.
        /// </summary>
        internal static string tvTitleRecieving {
            get {
                return ResourceManager.GetString("tvTitleRecieving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrepôt :.
        /// </summary>
        internal static string tvWarehouse {
            get {
                return ResourceManager.GetString("tvWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.ceritar.com.
        /// </summary>
        internal static string tvWebsite {
            get {
                return ResourceManager.GetString("tvWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poids (Kg).
        /// </summary>
        internal static string tvWeight {
            get {
                return ResourceManager.GetString("tvWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fournisseur.
        /// </summary>
        internal static string txtFournisseur {
            get {
                return ResourceManager.GetString("txtFournisseur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Rec..
        /// </summary>
        internal static string txtRec {
            get {
                return ResourceManager.GetString("txtRec", resourceCulture);
            }
        }
    }
}
