//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Mobility_Android.WebService.WorkOrder {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WorkOrderSoap", Namespace="https://ceritar.com/")]
    public partial class WorkOrder : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetStationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMaCompagnieOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLisensePoolOperationCompleted;
        
        private System.Threading.SendOrPostCallback TermiconPrintObjectDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback getProductFormatNRIWithProCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateLisensePoolOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWorkOrdersTermiconOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPrintObjectDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWorkOrdersRFOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWorkOrdersbyBatchRFOperationCompleted;
        
        private System.Threading.SendOrPostCallback StartWorkOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback StopWorkOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWorkOrderStatsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateBtExtrantLicOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListOfBalancesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WorkOrder() {
            this.Url = "http://svr-net15-temp/myceritar_miechko/services/inventory/workorder.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetStationsCompletedEventHandler GetStationsCompleted;
        
        /// <remarks/>
        public event GetMaCompagnieCompletedEventHandler GetMaCompagnieCompleted;
        
        /// <remarks/>
        public event GetLisensePoolCompletedEventHandler GetLisensePoolCompleted;
        
        /// <remarks/>
        public event TermiconPrintObjectDataCompletedEventHandler TermiconPrintObjectDataCompleted;
        
        /// <remarks/>
        public event getProductFormatNRIWithProCodeCompletedEventHandler getProductFormatNRIWithProCodeCompleted;
        
        /// <remarks/>
        public event UpdateLisensePoolCompletedEventHandler UpdateLisensePoolCompleted;
        
        /// <remarks/>
        public event GetWorkOrdersTermiconCompletedEventHandler GetWorkOrdersTermiconCompleted;
        
        /// <remarks/>
        public event GetPrintObjectDataCompletedEventHandler GetPrintObjectDataCompleted;
        
        /// <remarks/>
        public event GetWorkOrdersRFCompletedEventHandler GetWorkOrdersRFCompleted;
        
        /// <remarks/>
        public event GetWorkOrdersbyBatchRFCompletedEventHandler GetWorkOrdersbyBatchRFCompleted;
        
        /// <remarks/>
        public event StartWorkOrderCompletedEventHandler StartWorkOrderCompleted;
        
        /// <remarks/>
        public event StopWorkOrderCompletedEventHandler StopWorkOrderCompleted;
        
        /// <remarks/>
        public event GetWorkOrderStatsCompletedEventHandler GetWorkOrderStatsCompleted;
        
        /// <remarks/>
        public event CreateBtExtrantLicCompletedEventHandler CreateBtExtrantLicCompleted;
        
        /// <remarks/>
        public event GetListOfBalancesCompletedEventHandler GetListOfBalancesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ceritar.com/GetStations", RequestNamespace="https://ceritar.com/", ResponseNamespace="https://ceritar.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CR_ResultActionOfListOfWorkOrderStationWS GetStations(string securedToken) {
            object[] results = this.Invoke("GetStations", new object[] {
                        securedToken});
            return ((CR_ResultActionOfListOfWorkOrderStationWS)(results[0]));
        }
        
        /// <remarks/>
        public void GetStationsAsync(string securedToken) {
            this.GetStationsAsync(securedToken, null);
        }
        
        /// <remarks/>
        public void GetStationsAsync(string securedToken, object userState) {
            if ((this.GetStationsOperationCompleted == null)) {
                this.GetStationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStationsOperationCompleted);
            }
            this.InvokeAsync("GetStations", new object[] {
                        securedToken}, this.GetStationsOperationCompleted, userState);
        }
        
        private void OnGetStationsOperationCompleted(object arg) {
            if ((this.GetStationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStationsCompleted(this, new GetStationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ceritar.com/GetMaCompagnie", RequestNamespace="https://ceritar.com/", ResponseNamespace="https://ceritar.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CR_ResultActionOfMaCompagnieWs GetMaCompagnie(string securedToken) {
            object[] results = this.Invoke("GetMaCompagnie", new object[] {
                        securedToken});
            return ((CR_ResultActionOfMaCompagnieWs)(results[0]));
        }
        
        /// <remarks/>
        public void GetMaCompagnieAsync(string securedToken) {
            this.GetMaCompagnieAsync(securedToken, null);
        }
        
        /// <remarks/>
        public void GetMaCompagnieAsync(string securedToken, object userState) {
            if ((this.GetMaCompagnieOperationCompleted == null)) {
                this.GetMaCompagnieOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMaCompagnieOperationCompleted);
            }
            this.InvokeAsync("GetMaCompagnie", new object[] {
                        securedToken}, this.GetMaCompagnieOperationCompleted, userState);
        }
        
        private void OnGetMaCompagnieOperationCompleted(object arg) {
            if ((this.GetMaCompagnieCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMaCompagnieCompleted(this, new GetMaCompagnieCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ceritar.com/GetLisensePool", RequestNamespace="https://ceritar.com/", ResponseNamespace="https://ceritar.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CR_ResultActionOfListOfWorkOrderLisensePool GetLisensePool(string securedToken, int ligne) {
            object[] results = this.Invoke("GetLisensePool", new object[] {
                        securedToken,
                        ligne});
            return ((CR_ResultActionOfListOfWorkOrderLisensePool)(results[0]));
        }
        
        /// <remarks/>
        public void GetLisensePoolAsync(string securedToken, int ligne) {
            this.GetLisensePoolAsync(securedToken, ligne, null);
        }
        
        /// <remarks/>
        public void GetLisensePoolAsync(string securedToken, int ligne, object userState) {
            if ((this.GetLisensePoolOperationCompleted == null)) {
                this.GetLisensePoolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLisensePoolOperationCompleted);
            }
            this.InvokeAsync("GetLisensePool", new object[] {
                        securedToken,
                        ligne}, this.GetLisensePoolOperationCompleted, userState);
        }
        
        private void OnGetLisensePoolOperationCompleted(object arg) {
            if ((this.GetLisensePoolCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLisensePoolCompleted(this, new GetLisensePoolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ceritar.com/TermiconPrintObjectData", RequestNamespace="https://ceritar.com/", ResponseNamespace="https://ceritar.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CR_ResultActionOfListOfTermiconPrintObject TermiconPrintObjectData(string securedToken, string PalCode, string AllBatchNUmber) {
            object[] results = this.Invoke("TermiconPrintObjectData", new object[] {
                        securedToken,
                        PalCode,
                        AllBatchNUmber});
            return ((CR_ResultActionOfListOfTermiconPrintObject)(results[0]));
        }
        
        /// <remarks/>
        public void TermiconPrintObjectDataAsync(string securedToken, string PalCode, string AllBatchNUmber) {
            this.TermiconPrintObjectDataAsync(securedToken, PalCode, AllBatchNUmber, null);
        }
        
        /// <remarks/>
        public void TermiconPrintObjectDataAsync(string securedToken, string PalCode, string AllBatchNUmber, object userState) {
            if ((this.TermiconPrintObjectDataOperationCompleted == null)) {
                this.TermiconPrintObjectDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTermiconPrintObjectDataOperationCompleted);
            }
            this.InvokeAsync("TermiconPrintObjectData", new object[] {
                        securedToken,
                        PalCode,
                        AllBatchNUmber}, this.TermiconPrintObjectDataOperationCompleted, userState);
        }
        
        private void OnTermiconPrintObjectDataOperationCompleted(object arg) {
            if ((this.TermiconPrintObjectDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TermiconPrintObjectDataCompleted(this, new TermiconPrintObjectDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ceritar.com/getProductFormatNRIWithProCode", RequestNamespace="https://ceritar.com/", ResponseNamespace="https://ceritar.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CR_ResultActionOfInt32 getProductFormatNRIWithProCode(string securedToken, ref string ProCode) {
            object[] results = this.Invoke("getProductFormatNRIWithProCode", new object[] {
                        securedToken,
                        ProCode});
            ProCode = ((string)(results[1]));
            return ((CR_ResultActionOfInt32)(results[0]));
        }
        
        /// <remarks/>
        public void getProductFormatNRIWithProCodeAsync(string securedToken, string ProCode) {
            this.getProductFormatNRIWithProCodeAsync(securedToken, ProCode, null);
        }
        
        /// <remarks/>
        public void getProductFormatNRIWithProCodeAsync(string securedToken, string ProCode, object userState) {
            if ((this.getProductFormatNRIWithProCodeOperationCompleted == null)) {
                this.getProductFormatNRIWithProCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetProductFormatNRIWithProCodeOperationCompleted);
            }
            this.InvokeAsync("getProductFormatNRIWithProCode", new object[] {
                        securedToken,
                        ProCode}, this.getProductFormatNRIWithProCodeOperationCompleted, userState);
        }
        
        private void OngetProductFormatNRIWithProCodeOperationCompleted(object arg) {
            if ((this.getProductFormatNRIWithProCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getProductFormatNRIWithProCodeCompleted(this, new getProductFormatNRIWithProCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ceritar.com/UpdateLisensePool", RequestNamespace="https://ceritar.com/", ResponseNamespace="https://ceritar.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CR_ResultActionOfBoolean UpdateLisensePool(string securedToken, int[] lisensePoolIds) {
            object[] results = this.Invoke("UpdateLisensePool", new object[] {
                        securedToken,
                        lisensePoolIds});
            return ((CR_ResultActionOfBoolean)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateLisensePoolAsync(string securedToken, int[] lisensePoolIds) {
            this.UpdateLisensePoolAsync(securedToken, lisensePoolIds, null);
        }
        
        /// <remarks/>
        public void UpdateLisensePoolAsync(string securedToken, int[] lisensePoolIds, object userState) {
            if ((this.UpdateLisensePoolOperationCompleted == null)) {
                this.UpdateLisensePoolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateLisensePoolOperationCompleted);
            }
            this.InvokeAsync("UpdateLisensePool", new object[] {
                        securedToken,
                        lisensePoolIds}, this.UpdateLisensePoolOperationCompleted, userState);
        }
        
        private void OnUpdateLisensePoolOperationCompleted(object arg) {
            if ((this.UpdateLisensePoolCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateLisensePoolCompleted(this, new UpdateLisensePoolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ceritar.com/GetWorkOrdersTermicon", RequestNamespace="https://ceritar.com/", ResponseNamespace="https://ceritar.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CR_ResultActionOfListOfWorkOrderWS GetWorkOrdersTermicon(string securedToken, int stationId) {
            object[] results = this.Invoke("GetWorkOrdersTermicon", new object[] {
                        securedToken,
                        stationId});
            return ((CR_ResultActionOfListOfWorkOrderWS)(results[0]));
        }
        
        /// <remarks/>
        public void GetWorkOrdersTermiconAsync(string securedToken, int stationId) {
            this.GetWorkOrdersTermiconAsync(securedToken, stationId, null);
        }
        
        /// <remarks/>
        public void GetWorkOrdersTermiconAsync(string securedToken, int stationId, object userState) {
            if ((this.GetWorkOrdersTermiconOperationCompleted == null)) {
                this.GetWorkOrdersTermiconOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWorkOrdersTermiconOperationCompleted);
            }
            this.InvokeAsync("GetWorkOrdersTermicon", new object[] {
                        securedToken,
                        stationId}, this.GetWorkOrdersTermiconOperationCompleted, userState);
        }
        
        private void OnGetWorkOrdersTermiconOperationCompleted(object arg) {
            if ((this.GetWorkOrdersTermiconCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWorkOrdersTermiconCompleted(this, new GetWorkOrdersTermiconCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ceritar.com/GetPrintObjectData", RequestNamespace="https://ceritar.com/", ResponseNamespace="https://ceritar.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CR_ResultActionOfBoolean GetPrintObjectData(TermiconDataWS PrintObject) {
            object[] results = this.Invoke("GetPrintObjectData", new object[] {
                        PrintObject});
            return ((CR_ResultActionOfBoolean)(results[0]));
        }
        
        /// <remarks/>
        public void GetPrintObjectDataAsync(TermiconDataWS PrintObject) {
            this.GetPrintObjectDataAsync(PrintObject, null);
        }
        
        /// <remarks/>
        public void GetPrintObjectDataAsync(TermiconDataWS PrintObject, object userState) {
            if ((this.GetPrintObjectDataOperationCompleted == null)) {
                this.GetPrintObjectDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPrintObjectDataOperationCompleted);
            }
            this.InvokeAsync("GetPrintObjectData", new object[] {
                        PrintObject}, this.GetPrintObjectDataOperationCompleted, userState);
        }
        
        private void OnGetPrintObjectDataOperationCompleted(object arg) {
            if ((this.GetPrintObjectDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPrintObjectDataCompleted(this, new GetPrintObjectDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ceritar.com/GetWorkOrdersRF", RequestNamespace="https://ceritar.com/", ResponseNamespace="https://ceritar.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CR_ResultActionOfListOfWorkOrderWS GetWorkOrdersRF(string securedToken, int stationId) {
            object[] results = this.Invoke("GetWorkOrdersRF", new object[] {
                        securedToken,
                        stationId});
            return ((CR_ResultActionOfListOfWorkOrderWS)(results[0]));
        }
        
        /// <remarks/>
        public void GetWorkOrdersRFAsync(string securedToken, int stationId) {
            this.GetWorkOrdersRFAsync(securedToken, stationId, null);
        }
        
        /// <remarks/>
        public void GetWorkOrdersRFAsync(string securedToken, int stationId, object userState) {
            if ((this.GetWorkOrdersRFOperationCompleted == null)) {
                this.GetWorkOrdersRFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWorkOrdersRFOperationCompleted);
            }
            this.InvokeAsync("GetWorkOrdersRF", new object[] {
                        securedToken,
                        stationId}, this.GetWorkOrdersRFOperationCompleted, userState);
        }
        
        private void OnGetWorkOrdersRFOperationCompleted(object arg) {
            if ((this.GetWorkOrdersRFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWorkOrdersRFCompleted(this, new GetWorkOrdersRFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ceritar.com/GetWorkOrdersbyBatchRF", RequestNamespace="https://ceritar.com/", ResponseNamespace="https://ceritar.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CR_ResultActionOfWorkOrderWS GetWorkOrdersbyBatchRF(string securedToken, string LicId, string barCode) {
            object[] results = this.Invoke("GetWorkOrdersbyBatchRF", new object[] {
                        securedToken,
                        LicId,
                        barCode});
            return ((CR_ResultActionOfWorkOrderWS)(results[0]));
        }
        
        /// <remarks/>
        public void GetWorkOrdersbyBatchRFAsync(string securedToken, string LicId, string barCode) {
            this.GetWorkOrdersbyBatchRFAsync(securedToken, LicId, barCode, null);
        }
        
        /// <remarks/>
        public void GetWorkOrdersbyBatchRFAsync(string securedToken, string LicId, string barCode, object userState) {
            if ((this.GetWorkOrdersbyBatchRFOperationCompleted == null)) {
                this.GetWorkOrdersbyBatchRFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWorkOrdersbyBatchRFOperationCompleted);
            }
            this.InvokeAsync("GetWorkOrdersbyBatchRF", new object[] {
                        securedToken,
                        LicId,
                        barCode}, this.GetWorkOrdersbyBatchRFOperationCompleted, userState);
        }
        
        private void OnGetWorkOrdersbyBatchRFOperationCompleted(object arg) {
            if ((this.GetWorkOrdersbyBatchRFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWorkOrdersbyBatchRFCompleted(this, new GetWorkOrdersbyBatchRFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ceritar.com/StartWorkOrder", RequestNamespace="https://ceritar.com/", ResponseNamespace="https://ceritar.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CR_ResultActionOfBoolean StartWorkOrder(string securedToken, int workOrderId) {
            object[] results = this.Invoke("StartWorkOrder", new object[] {
                        securedToken,
                        workOrderId});
            return ((CR_ResultActionOfBoolean)(results[0]));
        }
        
        /// <remarks/>
        public void StartWorkOrderAsync(string securedToken, int workOrderId) {
            this.StartWorkOrderAsync(securedToken, workOrderId, null);
        }
        
        /// <remarks/>
        public void StartWorkOrderAsync(string securedToken, int workOrderId, object userState) {
            if ((this.StartWorkOrderOperationCompleted == null)) {
                this.StartWorkOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStartWorkOrderOperationCompleted);
            }
            this.InvokeAsync("StartWorkOrder", new object[] {
                        securedToken,
                        workOrderId}, this.StartWorkOrderOperationCompleted, userState);
        }
        
        private void OnStartWorkOrderOperationCompleted(object arg) {
            if ((this.StartWorkOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StartWorkOrderCompleted(this, new StartWorkOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ceritar.com/StopWorkOrder", RequestNamespace="https://ceritar.com/", ResponseNamespace="https://ceritar.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CR_ResultActionOfBoolean StopWorkOrder(string securedToken, int workOrderId, int userId) {
            object[] results = this.Invoke("StopWorkOrder", new object[] {
                        securedToken,
                        workOrderId,
                        userId});
            return ((CR_ResultActionOfBoolean)(results[0]));
        }
        
        /// <remarks/>
        public void StopWorkOrderAsync(string securedToken, int workOrderId, int userId) {
            this.StopWorkOrderAsync(securedToken, workOrderId, userId, null);
        }
        
        /// <remarks/>
        public void StopWorkOrderAsync(string securedToken, int workOrderId, int userId, object userState) {
            if ((this.StopWorkOrderOperationCompleted == null)) {
                this.StopWorkOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStopWorkOrderOperationCompleted);
            }
            this.InvokeAsync("StopWorkOrder", new object[] {
                        securedToken,
                        workOrderId,
                        userId}, this.StopWorkOrderOperationCompleted, userState);
        }
        
        private void OnStopWorkOrderOperationCompleted(object arg) {
            if ((this.StopWorkOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StopWorkOrderCompleted(this, new StopWorkOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ceritar.com/GetWorkOrderStats", RequestNamespace="https://ceritar.com/", ResponseNamespace="https://ceritar.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CR_ResultActionOfListOfString GetWorkOrderStats(string securedToken, int workOrderId, int lng) {
            object[] results = this.Invoke("GetWorkOrderStats", new object[] {
                        securedToken,
                        workOrderId,
                        lng});
            return ((CR_ResultActionOfListOfString)(results[0]));
        }
        
        /// <remarks/>
        public void GetWorkOrderStatsAsync(string securedToken, int workOrderId, int lng) {
            this.GetWorkOrderStatsAsync(securedToken, workOrderId, lng, null);
        }
        
        /// <remarks/>
        public void GetWorkOrderStatsAsync(string securedToken, int workOrderId, int lng, object userState) {
            if ((this.GetWorkOrderStatsOperationCompleted == null)) {
                this.GetWorkOrderStatsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWorkOrderStatsOperationCompleted);
            }
            this.InvokeAsync("GetWorkOrderStats", new object[] {
                        securedToken,
                        workOrderId,
                        lng}, this.GetWorkOrderStatsOperationCompleted, userState);
        }
        
        private void OnGetWorkOrderStatsOperationCompleted(object arg) {
            if ((this.GetWorkOrderStatsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWorkOrderStatsCompleted(this, new GetWorkOrderStatsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ceritar.com/CreateBtExtrantLic", RequestNamespace="https://ceritar.com/", ResponseNamespace="https://ceritar.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CR_ResultActionOfBoolean CreateBtExtrantLic(LisenseExtrant[] items, bool isFullPallet) {
            object[] results = this.Invoke("CreateBtExtrantLic", new object[] {
                        items,
                        isFullPallet});
            return ((CR_ResultActionOfBoolean)(results[0]));
        }
        
        /// <remarks/>
        public void CreateBtExtrantLicAsync(LisenseExtrant[] items, bool isFullPallet) {
            this.CreateBtExtrantLicAsync(items, isFullPallet, null);
        }
        
        /// <remarks/>
        public void CreateBtExtrantLicAsync(LisenseExtrant[] items, bool isFullPallet, object userState) {
            if ((this.CreateBtExtrantLicOperationCompleted == null)) {
                this.CreateBtExtrantLicOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateBtExtrantLicOperationCompleted);
            }
            this.InvokeAsync("CreateBtExtrantLic", new object[] {
                        items,
                        isFullPallet}, this.CreateBtExtrantLicOperationCompleted, userState);
        }
        
        private void OnCreateBtExtrantLicOperationCompleted(object arg) {
            if ((this.CreateBtExtrantLicCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateBtExtrantLicCompleted(this, new CreateBtExtrantLicCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ceritar.com/GetListOfBalances", RequestNamespace="https://ceritar.com/", ResponseNamespace="https://ceritar.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CR_ResultActionOfListOfWorkOrderBalanceObject GetListOfBalances(string securedToken) {
            object[] results = this.Invoke("GetListOfBalances", new object[] {
                        securedToken});
            return ((CR_ResultActionOfListOfWorkOrderBalanceObject)(results[0]));
        }
        
        /// <remarks/>
        public void GetListOfBalancesAsync(string securedToken) {
            this.GetListOfBalancesAsync(securedToken, null);
        }
        
        /// <remarks/>
        public void GetListOfBalancesAsync(string securedToken, object userState) {
            if ((this.GetListOfBalancesOperationCompleted == null)) {
                this.GetListOfBalancesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListOfBalancesOperationCompleted);
            }
            this.InvokeAsync("GetListOfBalances", new object[] {
                        securedToken}, this.GetListOfBalancesOperationCompleted, userState);
        }
        
        private void OnGetListOfBalancesOperationCompleted(object arg) {
            if ((this.GetListOfBalancesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListOfBalancesCompleted(this, new GetListOfBalancesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ceritar.com/")]
    public partial class CR_ResultActionOfListOfWorkOrderStationWS {
        
        private bool successField;
        
        private CR_ErrorMessage[] errorsField;
        
        private WorkOrderStationWS[] returnValueField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public CR_ErrorMessage[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        public WorkOrderStationWS[] ReturnValue {
            get {
                return this.returnValueField;
            }
            set {
                this.returnValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ceritar.com/")]
    public partial class CR_ErrorMessage {
        
        private int codeField;
        
        private string messageField;
        
        /// <remarks/>
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ceritar.com/")]
    public partial class WorkOrderBalanceObject {
        
        private int idField;
        
        private string codeField;
        
        private string portField;
        
        private string baudRateField;
        
        private string parityField;
        
        private string dataBitsField;
        
        private string stopBitField;
        
        private bool handleCrField;
        
        private int thresholdField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Port {
            get {
                return this.portField;
            }
            set {
                this.portField = value;
            }
        }
        
        /// <remarks/>
        public string BaudRate {
            get {
                return this.baudRateField;
            }
            set {
                this.baudRateField = value;
            }
        }
        
        /// <remarks/>
        public string Parity {
            get {
                return this.parityField;
            }
            set {
                this.parityField = value;
            }
        }
        
        /// <remarks/>
        public string DataBits {
            get {
                return this.dataBitsField;
            }
            set {
                this.dataBitsField = value;
            }
        }
        
        /// <remarks/>
        public string StopBit {
            get {
                return this.stopBitField;
            }
            set {
                this.stopBitField = value;
            }
        }
        
        /// <remarks/>
        public bool HandleCr {
            get {
                return this.handleCrField;
            }
            set {
                this.handleCrField = value;
            }
        }
        
        /// <remarks/>
        public int Threshold {
            get {
                return this.thresholdField;
            }
            set {
                this.thresholdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ceritar.com/")]
    public partial class CR_ResultActionOfListOfWorkOrderBalanceObject {
        
        private bool successField;
        
        private CR_ErrorMessage[] errorsField;
        
        private WorkOrderBalanceObject[] returnValueField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public CR_ErrorMessage[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        public WorkOrderBalanceObject[] ReturnValue {
            get {
                return this.returnValueField;
            }
            set {
                this.returnValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ceritar.com/")]
    public partial class LisenseExtrant {
        
        private string securedTokenField;
        
        private int workOrderIdField;
        
        private int productIdField;
        
        private decimal weightField;
        
        private System.DateTime packingDateField;
        
        private string lisenseCodeField;
        
        /// <remarks/>
        public string securedToken {
            get {
                return this.securedTokenField;
            }
            set {
                this.securedTokenField = value;
            }
        }
        
        /// <remarks/>
        public int workOrderId {
            get {
                return this.workOrderIdField;
            }
            set {
                this.workOrderIdField = value;
            }
        }
        
        /// <remarks/>
        public int productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        public decimal weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime packingDate {
            get {
                return this.packingDateField;
            }
            set {
                this.packingDateField = value;
            }
        }
        
        /// <remarks/>
        public string lisenseCode {
            get {
                return this.lisenseCodeField;
            }
            set {
                this.lisenseCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ceritar.com/")]
    public partial class CR_ResultActionOfListOfString {
        
        private bool successField;
        
        private CR_ErrorMessage[] errorsField;
        
        private string[] returnValueField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public CR_ErrorMessage[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        public string[] ReturnValue {
            get {
                return this.returnValueField;
            }
            set {
                this.returnValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ceritar.com/")]
    public partial class CR_ResultActionOfWorkOrderWS {
        
        private bool successField;
        
        private CR_ErrorMessage[] errorsField;
        
        private WorkOrderWS returnValueField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public CR_ErrorMessage[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        public WorkOrderWS ReturnValue {
            get {
                return this.returnValueField;
            }
            set {
                this.returnValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ceritar.com/")]
    public partial class WorkOrderWS {
        
        private int idField;
        
        private string templateCodeField;
        
        private string templateDescFrField;
        
        private string templateDescEnField;
        
        private System.Nullable<System.DateTime> dateDebutField;
        
        private System.Nullable<System.DateTime> dateFinField;
        
        private int productionLineField;
        
        private int cieNriField;
        
        private string cieCodeField;
        
        private string cieNomField;
        
        private bool cieMoiField;
        
        private string batchCodeField;
        
        private WorkOrderProductWS[] productsField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string TemplateCode {
            get {
                return this.templateCodeField;
            }
            set {
                this.templateCodeField = value;
            }
        }
        
        /// <remarks/>
        public string TemplateDescFr {
            get {
                return this.templateDescFrField;
            }
            set {
                this.templateDescFrField = value;
            }
        }
        
        /// <remarks/>
        public string TemplateDescEn {
            get {
                return this.templateDescEnField;
            }
            set {
                this.templateDescEnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dateDebut {
            get {
                return this.dateDebutField;
            }
            set {
                this.dateDebutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dateFin {
            get {
                return this.dateFinField;
            }
            set {
                this.dateFinField = value;
            }
        }
        
        /// <remarks/>
        public int ProductionLine {
            get {
                return this.productionLineField;
            }
            set {
                this.productionLineField = value;
            }
        }
        
        /// <remarks/>
        public int cieNri {
            get {
                return this.cieNriField;
            }
            set {
                this.cieNriField = value;
            }
        }
        
        /// <remarks/>
        public string cieCode {
            get {
                return this.cieCodeField;
            }
            set {
                this.cieCodeField = value;
            }
        }
        
        /// <remarks/>
        public string cieNom {
            get {
                return this.cieNomField;
            }
            set {
                this.cieNomField = value;
            }
        }
        
        /// <remarks/>
        public bool cieMoi {
            get {
                return this.cieMoiField;
            }
            set {
                this.cieMoiField = value;
            }
        }
        
        /// <remarks/>
        public string batchCode {
            get {
                return this.batchCodeField;
            }
            set {
                this.batchCodeField = value;
            }
        }
        
        /// <remarks/>
        public WorkOrderProductWS[] Products {
            get {
                return this.productsField;
            }
            set {
                this.productsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ceritar.com/")]
    public partial class WorkOrderProductWS {
        
        private int idField;
        
        private int workOderIdField;
        
        private int productIdField;
        
        private string productCodeField;
        
        private string productDescFrField;
        
        private string productDescEnField;
        
        private string productDescAltField;
        
        private decimal weightField;
        
        private decimal tareField;
        
        private string sSCCField;
        
        private bool isFixedWeightField;
        
        private string expeditionStateFrField;
        
        private string expeditionStateEnField;
        
        private string batchNumberField;
        
        private int packageTypeField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int WorkOderId {
            get {
                return this.workOderIdField;
            }
            set {
                this.workOderIdField = value;
            }
        }
        
        /// <remarks/>
        public int ProductId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        public string ProductCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
            }
        }
        
        /// <remarks/>
        public string productDescFr {
            get {
                return this.productDescFrField;
            }
            set {
                this.productDescFrField = value;
            }
        }
        
        /// <remarks/>
        public string ProductDescEn {
            get {
                return this.productDescEnField;
            }
            set {
                this.productDescEnField = value;
            }
        }
        
        /// <remarks/>
        public string ProductDescAlt {
            get {
                return this.productDescAltField;
            }
            set {
                this.productDescAltField = value;
            }
        }
        
        /// <remarks/>
        public decimal Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        public decimal Tare {
            get {
                return this.tareField;
            }
            set {
                this.tareField = value;
            }
        }
        
        /// <remarks/>
        public string SSCC {
            get {
                return this.sSCCField;
            }
            set {
                this.sSCCField = value;
            }
        }
        
        /// <remarks/>
        public bool IsFixedWeight {
            get {
                return this.isFixedWeightField;
            }
            set {
                this.isFixedWeightField = value;
            }
        }
        
        /// <remarks/>
        public string ExpeditionStateFr {
            get {
                return this.expeditionStateFrField;
            }
            set {
                this.expeditionStateFrField = value;
            }
        }
        
        /// <remarks/>
        public string ExpeditionStateEn {
            get {
                return this.expeditionStateEnField;
            }
            set {
                this.expeditionStateEnField = value;
            }
        }
        
        /// <remarks/>
        public string BatchNumber {
            get {
                return this.batchNumberField;
            }
            set {
                this.batchNumberField = value;
            }
        }
        
        /// <remarks/>
        public int PackageType {
            get {
                return this.packageTypeField;
            }
            set {
                this.packageTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ceritar.com/")]
    public partial class TermiconDataWS {
        
        private string pBarCodeField;
        
        private int workOrderIdField;
        
        /// <remarks/>
        public string pBarCode {
            get {
                return this.pBarCodeField;
            }
            set {
                this.pBarCodeField = value;
            }
        }
        
        /// <remarks/>
        public int WorkOrderId {
            get {
                return this.workOrderIdField;
            }
            set {
                this.workOrderIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ceritar.com/")]
    public partial class CR_ResultActionOfListOfWorkOrderWS {
        
        private bool successField;
        
        private CR_ErrorMessage[] errorsField;
        
        private WorkOrderWS[] returnValueField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public CR_ErrorMessage[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        public WorkOrderWS[] ReturnValue {
            get {
                return this.returnValueField;
            }
            set {
                this.returnValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ceritar.com/")]
    public partial class CR_ResultActionOfBoolean {
        
        private bool successField;
        
        private CR_ErrorMessage[] errorsField;
        
        private bool returnValueField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public CR_ErrorMessage[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        public bool ReturnValue {
            get {
                return this.returnValueField;
            }
            set {
                this.returnValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ceritar.com/")]
    public partial class CR_ResultActionOfInt32 {
        
        private bool successField;
        
        private CR_ErrorMessage[] errorsField;
        
        private int returnValueField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public CR_ErrorMessage[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        public int ReturnValue {
            get {
                return this.returnValueField;
            }
            set {
                this.returnValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ceritar.com/")]
    public partial class TermiconPrintObject {
        
        private string descEnField;
        
        private string descFrField;
        
        private string descAltField;
        
        private decimal weightKgField;
        
        private decimal weightLbField;
        
        private decimal brutWeightKgField;
        
        private decimal brutWeightLbField;
        
        private decimal tareKgField;
        
        private decimal tareLbField;
        
        private string cieNomField;
        
        private string cieNoField;
        
        private string cieAdresseField;
        
        private System.DateTime prodDateField;
        
        private string batchNumberField;
        
        private string statusField;
        
        private string preparedForField;
        
        private int productIdField;
        
        private string productCodeField;
        
        private string sSCCField;
        
        private int licenseIdField;
        
        private int workOrderIdField;
        
        private int lineNumberField;
        
        private int packagingTypeField;
        
        private string barCodeField;
        
        private string serialNumberField;
        
        /// <remarks/>
        public string DescEn {
            get {
                return this.descEnField;
            }
            set {
                this.descEnField = value;
            }
        }
        
        /// <remarks/>
        public string DescFr {
            get {
                return this.descFrField;
            }
            set {
                this.descFrField = value;
            }
        }
        
        /// <remarks/>
        public string DescAlt {
            get {
                return this.descAltField;
            }
            set {
                this.descAltField = value;
            }
        }
        
        /// <remarks/>
        public decimal WeightKg {
            get {
                return this.weightKgField;
            }
            set {
                this.weightKgField = value;
            }
        }
        
        /// <remarks/>
        public decimal WeightLb {
            get {
                return this.weightLbField;
            }
            set {
                this.weightLbField = value;
            }
        }
        
        /// <remarks/>
        public decimal BrutWeightKg {
            get {
                return this.brutWeightKgField;
            }
            set {
                this.brutWeightKgField = value;
            }
        }
        
        /// <remarks/>
        public decimal BrutWeightLb {
            get {
                return this.brutWeightLbField;
            }
            set {
                this.brutWeightLbField = value;
            }
        }
        
        /// <remarks/>
        public decimal TareKg {
            get {
                return this.tareKgField;
            }
            set {
                this.tareKgField = value;
            }
        }
        
        /// <remarks/>
        public decimal TareLb {
            get {
                return this.tareLbField;
            }
            set {
                this.tareLbField = value;
            }
        }
        
        /// <remarks/>
        public string CieNom {
            get {
                return this.cieNomField;
            }
            set {
                this.cieNomField = value;
            }
        }
        
        /// <remarks/>
        public string CieNo {
            get {
                return this.cieNoField;
            }
            set {
                this.cieNoField = value;
            }
        }
        
        /// <remarks/>
        public string CieAdresse {
            get {
                return this.cieAdresseField;
            }
            set {
                this.cieAdresseField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ProdDate {
            get {
                return this.prodDateField;
            }
            set {
                this.prodDateField = value;
            }
        }
        
        /// <remarks/>
        public string BatchNumber {
            get {
                return this.batchNumberField;
            }
            set {
                this.batchNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string PreparedFor {
            get {
                return this.preparedForField;
            }
            set {
                this.preparedForField = value;
            }
        }
        
        /// <remarks/>
        public int ProductId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        public string ProductCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
            }
        }
        
        /// <remarks/>
        public string SSCC {
            get {
                return this.sSCCField;
            }
            set {
                this.sSCCField = value;
            }
        }
        
        /// <remarks/>
        public int LicenseId {
            get {
                return this.licenseIdField;
            }
            set {
                this.licenseIdField = value;
            }
        }
        
        /// <remarks/>
        public int WorkOrderId {
            get {
                return this.workOrderIdField;
            }
            set {
                this.workOrderIdField = value;
            }
        }
        
        /// <remarks/>
        public int lineNumber {
            get {
                return this.lineNumberField;
            }
            set {
                this.lineNumberField = value;
            }
        }
        
        /// <remarks/>
        public int PackagingType {
            get {
                return this.packagingTypeField;
            }
            set {
                this.packagingTypeField = value;
            }
        }
        
        /// <remarks/>
        public string BarCode {
            get {
                return this.barCodeField;
            }
            set {
                this.barCodeField = value;
            }
        }
        
        /// <remarks/>
        public string SerialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ceritar.com/")]
    public partial class CR_ResultActionOfListOfTermiconPrintObject {
        
        private bool successField;
        
        private CR_ErrorMessage[] errorsField;
        
        private TermiconPrintObject[] returnValueField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public CR_ErrorMessage[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        public TermiconPrintObject[] ReturnValue {
            get {
                return this.returnValueField;
            }
            set {
                this.returnValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ceritar.com/")]
    public partial class WorkOrderLisensePool {
        
        private int idField;
        
        private int stationIdField;
        
        private int nbBoxesField;
        
        private string productCodeField;
        
        private System.DateTime packingDateField;
        
        private decimal netWeightField;
        
        private int lotIdField;
        
        private string palCodeField;
        
        private string sSCCField;
        
        private string batchNumberField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int StationId {
            get {
                return this.stationIdField;
            }
            set {
                this.stationIdField = value;
            }
        }
        
        /// <remarks/>
        public int NbBoxes {
            get {
                return this.nbBoxesField;
            }
            set {
                this.nbBoxesField = value;
            }
        }
        
        /// <remarks/>
        public string ProductCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime PackingDate {
            get {
                return this.packingDateField;
            }
            set {
                this.packingDateField = value;
            }
        }
        
        /// <remarks/>
        public decimal NetWeight {
            get {
                return this.netWeightField;
            }
            set {
                this.netWeightField = value;
            }
        }
        
        /// <remarks/>
        public int LotId {
            get {
                return this.lotIdField;
            }
            set {
                this.lotIdField = value;
            }
        }
        
        /// <remarks/>
        public string PalCode {
            get {
                return this.palCodeField;
            }
            set {
                this.palCodeField = value;
            }
        }
        
        /// <remarks/>
        public string SSCC {
            get {
                return this.sSCCField;
            }
            set {
                this.sSCCField = value;
            }
        }
        
        /// <remarks/>
        public string BatchNumber {
            get {
                return this.batchNumberField;
            }
            set {
                this.batchNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ceritar.com/")]
    public partial class CR_ResultActionOfListOfWorkOrderLisensePool {
        
        private bool successField;
        
        private CR_ErrorMessage[] errorsField;
        
        private WorkOrderLisensePool[] returnValueField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public CR_ErrorMessage[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        public WorkOrderLisensePool[] ReturnValue {
            get {
                return this.returnValueField;
            }
            set {
                this.returnValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ceritar.com/")]
    public partial class MaCompagnieWs {
        
        private int idField;
        
        private string nomField;
        
        private string numeroField;
        
        private string adresseField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nom {
            get {
                return this.nomField;
            }
            set {
                this.nomField = value;
            }
        }
        
        /// <remarks/>
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string Adresse {
            get {
                return this.adresseField;
            }
            set {
                this.adresseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ceritar.com/")]
    public partial class CR_ResultActionOfMaCompagnieWs {
        
        private bool successField;
        
        private CR_ErrorMessage[] errorsField;
        
        private MaCompagnieWs returnValueField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public CR_ErrorMessage[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        public MaCompagnieWs ReturnValue {
            get {
                return this.returnValueField;
            }
            set {
                this.returnValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ceritar.com/")]
    public partial class WorkOrderStationWS {
        
        private int idField;
        
        private string codeField;
        
        private int lineNumberField;
        
        private int productionLineField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public int LineNumber {
            get {
                return this.lineNumberField;
            }
            set {
                this.lineNumberField = value;
            }
        }
        
        /// <remarks/>
        public int ProductionLine {
            get {
                return this.productionLineField;
            }
            set {
                this.productionLineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void GetStationsCompletedEventHandler(object sender, GetStationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CR_ResultActionOfListOfWorkOrderStationWS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CR_ResultActionOfListOfWorkOrderStationWS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void GetMaCompagnieCompletedEventHandler(object sender, GetMaCompagnieCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMaCompagnieCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMaCompagnieCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CR_ResultActionOfMaCompagnieWs Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CR_ResultActionOfMaCompagnieWs)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void GetLisensePoolCompletedEventHandler(object sender, GetLisensePoolCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLisensePoolCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLisensePoolCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CR_ResultActionOfListOfWorkOrderLisensePool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CR_ResultActionOfListOfWorkOrderLisensePool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void TermiconPrintObjectDataCompletedEventHandler(object sender, TermiconPrintObjectDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TermiconPrintObjectDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TermiconPrintObjectDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CR_ResultActionOfListOfTermiconPrintObject Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CR_ResultActionOfListOfTermiconPrintObject)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void getProductFormatNRIWithProCodeCompletedEventHandler(object sender, getProductFormatNRIWithProCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getProductFormatNRIWithProCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getProductFormatNRIWithProCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CR_ResultActionOfInt32 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CR_ResultActionOfInt32)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string ProCode {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void UpdateLisensePoolCompletedEventHandler(object sender, UpdateLisensePoolCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateLisensePoolCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateLisensePoolCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CR_ResultActionOfBoolean Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CR_ResultActionOfBoolean)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void GetWorkOrdersTermiconCompletedEventHandler(object sender, GetWorkOrdersTermiconCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWorkOrdersTermiconCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWorkOrdersTermiconCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CR_ResultActionOfListOfWorkOrderWS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CR_ResultActionOfListOfWorkOrderWS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void GetPrintObjectDataCompletedEventHandler(object sender, GetPrintObjectDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPrintObjectDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPrintObjectDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CR_ResultActionOfBoolean Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CR_ResultActionOfBoolean)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void GetWorkOrdersRFCompletedEventHandler(object sender, GetWorkOrdersRFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWorkOrdersRFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWorkOrdersRFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CR_ResultActionOfListOfWorkOrderWS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CR_ResultActionOfListOfWorkOrderWS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void GetWorkOrdersbyBatchRFCompletedEventHandler(object sender, GetWorkOrdersbyBatchRFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWorkOrdersbyBatchRFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWorkOrdersbyBatchRFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CR_ResultActionOfWorkOrderWS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CR_ResultActionOfWorkOrderWS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void StartWorkOrderCompletedEventHandler(object sender, StartWorkOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StartWorkOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StartWorkOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CR_ResultActionOfBoolean Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CR_ResultActionOfBoolean)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void StopWorkOrderCompletedEventHandler(object sender, StopWorkOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StopWorkOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StopWorkOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CR_ResultActionOfBoolean Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CR_ResultActionOfBoolean)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void GetWorkOrderStatsCompletedEventHandler(object sender, GetWorkOrderStatsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWorkOrderStatsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWorkOrderStatsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CR_ResultActionOfListOfString Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CR_ResultActionOfListOfString)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void CreateBtExtrantLicCompletedEventHandler(object sender, CreateBtExtrantLicCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateBtExtrantLicCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateBtExtrantLicCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CR_ResultActionOfBoolean Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CR_ResultActionOfBoolean)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void GetListOfBalancesCompletedEventHandler(object sender, GetListOfBalancesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListOfBalancesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListOfBalancesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CR_ResultActionOfListOfWorkOrderBalanceObject Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CR_ResultActionOfListOfWorkOrderBalanceObject)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591