//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Mobility_Android.WebService.Security {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SecuritySoap", Namespace="https://ceritar.com/")]
    public partial class Security : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback authentificateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback disconnectUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserInfosOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveUserInfosOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListWarehousesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListCompaniesOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateUserWarehouseOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Security() {
            this.Url = "http://svr-net15-temp/myceritar_miechko/services/security.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event authentificateUserCompletedEventHandler authentificateUserCompleted;
        
        /// <remarks/>
        public event disconnectUserCompletedEventHandler disconnectUserCompleted;
        
        /// <remarks/>
        public event GetUserInfosCompletedEventHandler GetUserInfosCompleted;
        
        /// <remarks/>
        public event SaveUserInfosCompletedEventHandler SaveUserInfosCompleted;
        
        /// <remarks/>
        public event GetListWarehousesCompletedEventHandler GetListWarehousesCompleted;
        
        /// <remarks/>
        public event GetListCompaniesCompletedEventHandler GetListCompaniesCompleted;
        
        /// <remarks/>
        public event UpdateUserWarehouseCompletedEventHandler UpdateUserWarehouseCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ceritar.com/authentificateUser", RequestNamespace="https://ceritar.com/", ResponseNamespace="https://ceritar.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CR_ResultActionOfCR_WebAuthentification authentificateUser(string login, string password, CR_TTLangue language) {
            object[] results = this.Invoke("authentificateUser", new object[] {
                        login,
                        password,
                        language});
            return ((CR_ResultActionOfCR_WebAuthentification)(results[0]));
        }
        
        /// <remarks/>
        public void authentificateUserAsync(string login, string password, CR_TTLangue language) {
            this.authentificateUserAsync(login, password, language, null);
        }
        
        /// <remarks/>
        public void authentificateUserAsync(string login, string password, CR_TTLangue language, object userState) {
            if ((this.authentificateUserOperationCompleted == null)) {
                this.authentificateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnauthentificateUserOperationCompleted);
            }
            this.InvokeAsync("authentificateUser", new object[] {
                        login,
                        password,
                        language}, this.authentificateUserOperationCompleted, userState);
        }
        
        private void OnauthentificateUserOperationCompleted(object arg) {
            if ((this.authentificateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.authentificateUserCompleted(this, new authentificateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ceritar.com/disconnectUser", RequestNamespace="https://ceritar.com/", ResponseNamespace="https://ceritar.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CR_ResultActionOfBoolean disconnectUser(string securedToken) {
            object[] results = this.Invoke("disconnectUser", new object[] {
                        securedToken});
            return ((CR_ResultActionOfBoolean)(results[0]));
        }
        
        /// <remarks/>
        public void disconnectUserAsync(string securedToken) {
            this.disconnectUserAsync(securedToken, null);
        }
        
        /// <remarks/>
        public void disconnectUserAsync(string securedToken, object userState) {
            if ((this.disconnectUserOperationCompleted == null)) {
                this.disconnectUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OndisconnectUserOperationCompleted);
            }
            this.InvokeAsync("disconnectUser", new object[] {
                        securedToken}, this.disconnectUserOperationCompleted, userState);
        }
        
        private void OndisconnectUserOperationCompleted(object arg) {
            if ((this.disconnectUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.disconnectUserCompleted(this, new disconnectUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ceritar.com/GetUserInfos", RequestNamespace="https://ceritar.com/", ResponseNamespace="https://ceritar.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CR_ResultActionOfUserInfosWS GetUserInfos(string securedToken) {
            object[] results = this.Invoke("GetUserInfos", new object[] {
                        securedToken});
            return ((CR_ResultActionOfUserInfosWS)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserInfosAsync(string securedToken) {
            this.GetUserInfosAsync(securedToken, null);
        }
        
        /// <remarks/>
        public void GetUserInfosAsync(string securedToken, object userState) {
            if ((this.GetUserInfosOperationCompleted == null)) {
                this.GetUserInfosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserInfosOperationCompleted);
            }
            this.InvokeAsync("GetUserInfos", new object[] {
                        securedToken}, this.GetUserInfosOperationCompleted, userState);
        }
        
        private void OnGetUserInfosOperationCompleted(object arg) {
            if ((this.GetUserInfosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserInfosCompleted(this, new GetUserInfosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ceritar.com/SaveUserInfos", RequestNamespace="https://ceritar.com/", ResponseNamespace="https://ceritar.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CR_ResultActionOfBoolean SaveUserInfos(string securedToken, UserInfosWS infos) {
            object[] results = this.Invoke("SaveUserInfos", new object[] {
                        securedToken,
                        infos});
            return ((CR_ResultActionOfBoolean)(results[0]));
        }
        
        /// <remarks/>
        public void SaveUserInfosAsync(string securedToken, UserInfosWS infos) {
            this.SaveUserInfosAsync(securedToken, infos, null);
        }
        
        /// <remarks/>
        public void SaveUserInfosAsync(string securedToken, UserInfosWS infos, object userState) {
            if ((this.SaveUserInfosOperationCompleted == null)) {
                this.SaveUserInfosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveUserInfosOperationCompleted);
            }
            this.InvokeAsync("SaveUserInfos", new object[] {
                        securedToken,
                        infos}, this.SaveUserInfosOperationCompleted, userState);
        }
        
        private void OnSaveUserInfosOperationCompleted(object arg) {
            if ((this.SaveUserInfosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveUserInfosCompleted(this, new SaveUserInfosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ceritar.com/GetListWarehouses", RequestNamespace="https://ceritar.com/", ResponseNamespace="https://ceritar.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CR_ResultActionOfListOfWarehouseObject GetListWarehouses(string securedToken, int[] warehousesToExclude) {
            object[] results = this.Invoke("GetListWarehouses", new object[] {
                        securedToken,
                        warehousesToExclude});
            return ((CR_ResultActionOfListOfWarehouseObject)(results[0]));
        }
        
        /// <remarks/>
        public void GetListWarehousesAsync(string securedToken, int[] warehousesToExclude) {
            this.GetListWarehousesAsync(securedToken, warehousesToExclude, null);
        }
        
        /// <remarks/>
        public void GetListWarehousesAsync(string securedToken, int[] warehousesToExclude, object userState) {
            if ((this.GetListWarehousesOperationCompleted == null)) {
                this.GetListWarehousesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListWarehousesOperationCompleted);
            }
            this.InvokeAsync("GetListWarehouses", new object[] {
                        securedToken,
                        warehousesToExclude}, this.GetListWarehousesOperationCompleted, userState);
        }
        
        private void OnGetListWarehousesOperationCompleted(object arg) {
            if ((this.GetListWarehousesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListWarehousesCompleted(this, new GetListWarehousesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ceritar.com/GetListCompanies", RequestNamespace="https://ceritar.com/", ResponseNamespace="https://ceritar.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CR_ResultActionOfListOfCompanyObjectWS GetListCompanies(string securedToken, int companyType) {
            object[] results = this.Invoke("GetListCompanies", new object[] {
                        securedToken,
                        companyType});
            return ((CR_ResultActionOfListOfCompanyObjectWS)(results[0]));
        }
        
        /// <remarks/>
        public void GetListCompaniesAsync(string securedToken, int companyType) {
            this.GetListCompaniesAsync(securedToken, companyType, null);
        }
        
        /// <remarks/>
        public void GetListCompaniesAsync(string securedToken, int companyType, object userState) {
            if ((this.GetListCompaniesOperationCompleted == null)) {
                this.GetListCompaniesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListCompaniesOperationCompleted);
            }
            this.InvokeAsync("GetListCompanies", new object[] {
                        securedToken,
                        companyType}, this.GetListCompaniesOperationCompleted, userState);
        }
        
        private void OnGetListCompaniesOperationCompleted(object arg) {
            if ((this.GetListCompaniesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListCompaniesCompleted(this, new GetListCompaniesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ceritar.com/UpdateUserWarehouse", RequestNamespace="https://ceritar.com/", ResponseNamespace="https://ceritar.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CR_ResultActionOfBoolean UpdateUserWarehouse(string securedToken, int newWarehouseNRI) {
            object[] results = this.Invoke("UpdateUserWarehouse", new object[] {
                        securedToken,
                        newWarehouseNRI});
            return ((CR_ResultActionOfBoolean)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateUserWarehouseAsync(string securedToken, int newWarehouseNRI) {
            this.UpdateUserWarehouseAsync(securedToken, newWarehouseNRI, null);
        }
        
        /// <remarks/>
        public void UpdateUserWarehouseAsync(string securedToken, int newWarehouseNRI, object userState) {
            if ((this.UpdateUserWarehouseOperationCompleted == null)) {
                this.UpdateUserWarehouseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateUserWarehouseOperationCompleted);
            }
            this.InvokeAsync("UpdateUserWarehouse", new object[] {
                        securedToken,
                        newWarehouseNRI}, this.UpdateUserWarehouseOperationCompleted, userState);
        }
        
        private void OnUpdateUserWarehouseOperationCompleted(object arg) {
            if ((this.UpdateUserWarehouseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateUserWarehouseCompleted(this, new UpdateUserWarehouseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ceritar.com/")]
    public enum CR_TTLangue {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        French_Canada,
        
        /// <remarks/>
        English,
        
        /// <remarks/>
        Spanish,
        
        /// <remarks/>
        French_France,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ceritar.com/")]
    public partial class CR_ResultActionOfCR_WebAuthentification {
        
        private bool successField;
        
        private CR_ErrorMessage[] errorsField;
        
        private CR_WebAuthentification returnValueField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public CR_ErrorMessage[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        public CR_WebAuthentification ReturnValue {
            get {
                return this.returnValueField;
            }
            set {
                this.returnValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ceritar.com/")]
    public partial class CR_ErrorMessage {
        
        private int codeField;
        
        private string messageField;
        
        /// <remarks/>
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ceritar.com/")]
    public partial class CompanyObjectWS {
        
        private int nRIField;
        
        private string codeField;
        
        /// <remarks/>
        public int NRI {
            get {
                return this.nRIField;
            }
            set {
                this.nRIField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ceritar.com/")]
    public partial class CR_ResultActionOfListOfCompanyObjectWS {
        
        private bool successField;
        
        private CR_ErrorMessage[] errorsField;
        
        private CompanyObjectWS[] returnValueField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public CR_ErrorMessage[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        public CompanyObjectWS[] ReturnValue {
            get {
                return this.returnValueField;
            }
            set {
                this.returnValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ceritar.com/")]
    public partial class WarehouseObject {
        
        private int idField;
        
        private string codeField;
        
        private string descriptionEnField;
        
        private string descriptionFrField;
        
        private int defaultLocationIdField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string DescriptionEn {
            get {
                return this.descriptionEnField;
            }
            set {
                this.descriptionEnField = value;
            }
        }
        
        /// <remarks/>
        public string DescriptionFr {
            get {
                return this.descriptionFrField;
            }
            set {
                this.descriptionFrField = value;
            }
        }
        
        /// <remarks/>
        public int DefaultLocationId {
            get {
                return this.defaultLocationIdField;
            }
            set {
                this.defaultLocationIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ceritar.com/")]
    public partial class CR_ResultActionOfListOfWarehouseObject {
        
        private bool successField;
        
        private CR_ErrorMessage[] errorsField;
        
        private WarehouseObject[] returnValueField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public CR_ErrorMessage[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        public WarehouseObject[] ReturnValue {
            get {
                return this.returnValueField;
            }
            set {
                this.returnValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ceritar.com/")]
    public partial class UserInfosWS {
        
        private int nRIField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private int warehouseNRIField;
        
        /// <remarks/>
        public int NRI {
            get {
                return this.nRIField;
            }
            set {
                this.nRIField = value;
            }
        }
        
        /// <remarks/>
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public int warehouseNRI {
            get {
                return this.warehouseNRIField;
            }
            set {
                this.warehouseNRIField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ceritar.com/")]
    public partial class CR_ResultActionOfUserInfosWS {
        
        private bool successField;
        
        private CR_ErrorMessage[] errorsField;
        
        private UserInfosWS returnValueField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public CR_ErrorMessage[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        public UserInfosWS ReturnValue {
            get {
                return this.returnValueField;
            }
            set {
                this.returnValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ceritar.com/")]
    public partial class CR_ResultActionOfBoolean {
        
        private bool successField;
        
        private CR_ErrorMessage[] errorsField;
        
        private bool returnValueField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public CR_ErrorMessage[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        public bool ReturnValue {
            get {
                return this.returnValueField;
            }
            set {
                this.returnValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ceritar.com/")]
    public partial class CR_WebAuthentification {
        
        private string tokenField;
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void authentificateUserCompletedEventHandler(object sender, authentificateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class authentificateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal authentificateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CR_ResultActionOfCR_WebAuthentification Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CR_ResultActionOfCR_WebAuthentification)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void disconnectUserCompletedEventHandler(object sender, disconnectUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class disconnectUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal disconnectUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CR_ResultActionOfBoolean Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CR_ResultActionOfBoolean)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void GetUserInfosCompletedEventHandler(object sender, GetUserInfosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserInfosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserInfosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CR_ResultActionOfUserInfosWS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CR_ResultActionOfUserInfosWS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void SaveUserInfosCompletedEventHandler(object sender, SaveUserInfosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveUserInfosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveUserInfosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CR_ResultActionOfBoolean Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CR_ResultActionOfBoolean)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void GetListWarehousesCompletedEventHandler(object sender, GetListWarehousesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListWarehousesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListWarehousesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CR_ResultActionOfListOfWarehouseObject Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CR_ResultActionOfListOfWarehouseObject)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void GetListCompaniesCompletedEventHandler(object sender, GetListCompaniesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListCompaniesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListCompaniesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CR_ResultActionOfListOfCompanyObjectWS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CR_ResultActionOfListOfCompanyObjectWS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void UpdateUserWarehouseCompletedEventHandler(object sender, UpdateUserWarehouseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateUserWarehouseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateUserWarehouseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CR_ResultActionOfBoolean Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CR_ResultActionOfBoolean)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591